version: '2'
services:

# Container responsible for running the pipeline
  ergatis:
    environment:
      - DOCKER_HOST=localhost
      - REPO_ROOT=/opt/projects/rnaseq/
      - TEMPLATES=/opt/ergatis/pipeline_templates/
    image: adkinsrs/rnaseq:latest
#    links:
#      - post # Will rename once Amol creates his UI
    ports:
      - "8080:80"
    volumes:
      - ergatis_vol:/opt/ergatis
#    volumes_from:
#      - builder

# Container with the pipeline configuration UI 
  builder:
    image: grotto
    links:
      - ergatis
    ports:
      - "5000:5000"
    volumes_from:
      - ergatis
    volumes:
      - ~/bin/grotto/www:/app

# Container to view post-analysis data
#  post:
#    build: .
#    volumes_from: ergatis.

volumes:
  ergatis_vol:
