version: '2'
services:

# docker-compose.yml is for development purposes.
# To create a production version of docker-compose.yml, run the setup_container.sh script which uses docker-compose.tmpl.yml to build it
  ergatis:
    build: .
    #image: adkinsrs/lgtseek
    links:
      - mongo
    mem_limit: 5120000000
    ports:
      - "8080:80"
    volumes:
      - ./input_data:/mnt/input_data:ro
      - ./output_data:/mnt/output_data
      - ./split_multifasta.fsa.list:/mnt/split_multifasta.fsa.list
      - ./pipeline_builder:/var/www/html/pipeline_builder
    volumes_from:
      - mongodata

  mongo:
    image: mongo:2.6
    volumes_from:
      - mongodata
    ports:
      - "27017:27017"
    command: --smallfiles

# Mongodata is necessary for persistent data storage
# MongoDB normally wipes data when shut down
  mongodata:
    image: mongo:2.6
    volumes:
      - /data/db
    command: --break-mongo
