version: '2'
services:

  ergatis:
    build: .
    volumes:
      - ./input_data:/mnt/input_data:ro
      - ./output_data:/mnt/output_data
      - ./split_multifasta.fsa.list:/mnt/split_multifasta.fsa.list
      - ./pipeline_builder:/var/www/html/pipeline_builder

