# Grotto
# Flask-based UI to build and launch a RNAseq transcripomics pipeline

# Install R stuff.  Do not need "dev" stuff
# TODO: get off of this image since it uses alpine:edge instead of a stable version
FROM conoria/alpine-pandoc:latest AS build

WORKDIR /usr/share/doc/R/html

# R is version 4.0 here so main image needs to match up
#RUN apk add R R-dev alpine-sdk perl
RUN apk add alpine-sdk perl

# R packages for report generation
#COPY install_r_pkgs.sh /tmp/.
#RUN /tmp/install_r_pkgs.sh

########
FROM adkinsrs/ergatis:alpine
LABEL maintainer="Shaun Adkins <sadkins@som.umaryland.edu>"

EXPOSE 5000

ARG REPORT_DOWNLOAD_URL=https://github.com/IGS/report-generator.git

RUN apk --update add --no-cache \
  #expat-dev \
  #make \
  #gcc \
  #g++ \
  libffi-dev \
  readline-dev \
  xz-dev \
  xz-libs \
  bzip2-dev \
  pcre-dev \
  openblas-dev \
  krb5-dev \
  curl-dev \
  python3-dev \
  py3-setuptools \
  py3-pip \
  py3-dateutil \
  py3-requests \
  py3-urllib3 \
  py3-certifi \
  # Report generator dependencies
  #R \
  #R-dev \
  gfortran \
  imagemagick6 \
  #cargo \
  tesseract-ocr \
  zip unzip
  # \
  #texmf-dist texmf-dist-latexextra

WORKDIR /usr/src

# Install R
RUN wget http://cran.rstudio.com/src/base/R-3/R-3.5.1.tar.gz \
  && tar xvf R-3.5.1.tar.gz \
  && cd R-3.5.1 \
  && ./configure --enable-R-shlib --with-x=no \
  && make && make install

# Get R packages and pandoc
#COPY --from=build /usr/lib/R /usr/lib/R
COPY --from=build /usr/bin/pandoc /usr/bin/pandoc
COPY --from=build /usr/share/pandoc /usr/share/pandoc
COPY --from=build /usr/lib/libgmp.so.10 /usr/lib/libgmp.so.10
#COPY --from=build /usr/lib/libicudata.so.60 /usr/lib/libicudata.so.60
#COPY --from=build /usr/lib/libreadline.so.8 /usr/lib/libreadline.so.8
#COPY --from=build /usr/lib/libicuuc.so.60.2 /usr/lib/libicuuc.so.60
#COPY --from=build /usr/lib/libicui18n.so.60.2 /usr/lib/libicui18n.so.60
#COPY --from=build /usr/lib/R/library/Rcpp/libs/Rcpp.so /usr/lib/R/library/Rcpp/libs/Rcpp.so

RUN pip3 install --upgrade pip \
# Flask version in alpine packages is <1.0.
  #&& pip3 install --no-cache-dir bagit bdbag python-dotenv tzlocal flask flask_login flask_session pandas kerberos rpy2
  && pip3 install --no-cache-dir bagit bdbag python-dotenv tzlocal flask flask_login flask_session pandas kerberos

# Install Report generator
RUN git clone --single-branch --branch wrap $REPORT_DOWNLOAD_URL \
	&& cd report-generator \
	&& ln -s /usr/src/report-generator/scripts/bdbag_generator.py /opt/bdbag_generator.py \
	&& ln -s /usr/src/report-generator/scripts/report_generator.py /opt/report_generator.py \
  && ln -s /usr/src/report-generator/wrappers /opt/wrappers \
  && ln -s /usr/src/report-generator/RMD /opt/RMD \
	&& chmod 755 /opt/*

# Add Ergatis package-rnaseq repo so that volumes don't have to be shared
COPY --from=adkinsrs/rnaseq:latest /opt/ergatis/ /opt/ergatis/

COPY . /app
WORKDIR /app
RUN mkdir -m 0777 -p /app/application/static/tmp

ENV FLASK_ENV=development
# Needed for rpy2 module
ENV LD_LIBRARY_PATH="/usr/lib/R/lib:$LD_LIBRARY_PATH"

ENTRYPOINT ["python3"]
CMD ["wsgi.py"]
